site_name: Séminaire Algortihmie
site_url: https://yostane.github.io/jeu-de-la-vie/
repo_url: https://github.com/yostane/jeu-de-la-vie
repo_name: yostane/jeu-de-la-vie
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yostane

nav:
  - Accueil: index.md
  - Rappels de Python: python-tour.ipynb
  - Notions avancées de Python: python-avance.ipynb

plugins:
  - mkdocs-jupyter:
      execute: True
  - search
  - tags:
      tags_file: tags.md

theme:
  logo: img/logo.jpg
  favicon: img/logo.jpg
  name: material
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: light green
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: light green

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: ["material/"]
